### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by bjpbakker**
Add a scheme for the Dezignables framework and share it in the Xcode project so that Carthage is able to build Dezignables.

Also replace Cocoapods with Carthage for the test dependency.

### CODE REVIEW

**Comment by bjpbakker** [comment]
@s0meone any thoughts? :)

**Comment by s0meone** [comment]
Tried this, didn't work yet.

When running `carthage update` since I expect that this was needed to get the Example project running again. Building without this complained that the test dependencies were missing (FBSnapshotCase).

But the command gave me the following output:

```
Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.2

=== BUILD TARGET FBSnapshotTestCase tvOS OF PROJECT FBSnapshotTestCase WITH CONFIGURATION Release ===

Check dependencies

Ld /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64
    cd /Users/daniel/Development/Workspaces/code/Dezignables/Example/Carthage/Checkouts/ios-snapshot-test-case
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/heroku/bin:/usr/local/opt/rbenv/shims:/usr/local/share/npm/bin:/usr/local/heroku/bin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/daniel/Development/Tools/jakarta-jmeter-2.4/bin"
    export TVOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS9.2.sdk -L/Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Products/Release-appletvos -F/Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Products/Release-appletvos -F/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks -filelist /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Intermediates/FBSnapshotTestCase.build/Release-appletvos/FBSnapshotTestCase\ tvOS.build/Objects-normal/arm64/FBSnapshotTestCase.LinkFileList -install_name @rpath/FBSnapshotTestCase.framework/FBSnapshotTestCase -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mtvos-version-min=9.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Products/Release-appletvos -framework XCTest -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/appletvos -Xlinker -add_ast_path -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Intermediates/FBSnapshotTestCase.build/Release-appletvos/FBSnapshotTestCase\ tvOS.build/Objects-normal/arm64/FBSnapshotTestCase.swiftmodule -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Intermediates/FBSnapshotTestCase.build/Release-appletvos/FBSnapshotTestCase\ tvOS.build/Objects-normal/arm64/FBSnapshotTestCase_dependency_info.dat -o /Users/daniel/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-gzbzrfyrnczhgqggdzbvcpxfpeud/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure why it's busy installing TVOS stuff. And why is the workspace file empty? If we don't need it anymore it can be removed.

How do I get this working?

**Comment by bjpbakker** [comment]
``` sh
$ carthage bootstrap --no-use-binaries --platform ios
```

Limit the platforms to build to iOS. Apparently `FBSnapshotTestCase` does not build for tv-os.

**Comment by bjpbakker** [comment]
Ping @s0meone - any chance we can merge this?

**Comment by s0meone** [comment]
Got the Example project to build, so this works.

**Pull request merged**
